---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rukpak-webhook-certificate
  namespace: openshift-rukpak-system
spec:
  dnsNames:
    - rukpak-webhook-service.openshift-rukpak-system.svc
    - rukpak-webhook-service.openshift-rukpak-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: rukpak-selfsigned
  secretName: rukpak-webhook-certificate
