---
apiVersion: v1
kind: Service
metadata:
  name: crd-validation-webhook
  namespace: openshift-crdvalidator-system
spec:
  ports:
    - port: 9443
      protocol: TCP
      targetPort: 9443
  selector:
    app: crd-validation-webhook
