---
apiVersion: v1
kind: Service
metadata:
  name: core
  namespace: openshift-rukpak-system
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app: core
