---
apiVersion: v1
kind: Service
metadata:
  name: rukpak-webhook-service
  namespace: openshift-rukpak-system
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    app: webhooks
