---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: crd-validation-webhook-certificate
  namespace: openshift-crdvalidator-system
spec:
  dnsNames:
    - crd-validation-webhook.openshift-crdvalidator-system.svc
  issuerRef:
    name: selfsigned
  secretName: crd-validation-webhook-certificate
