---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: core
  namespace: openshift-rukpak-system
spec:
  dnsNames:
    - localhost
    - core.openshift-rukpak-system.svc
    - core.openshift-rukpak-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: rukpak-ca-issuer
  secretName: core-cert
